# Generated by Django 4.2.4 on 2025-02-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name"
            ),
        ),
    ]
